branches:
  only:
    - master
    - dev
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

cache:
  npm: true

language: node_js
node_js:
  - node

install:
  - npm install

script:
  - npm run build

before_deploy:
  - tar -czvf dist.tar.gz dist

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file: dist.tar.gz
  skip_cleanup: true
  on:
    branch: master
    tags: true
